CXX = g++
CXXFLAGS = -std=c++11 -Wall -pedantic
CL = rm

build:
	# $(CXX) $(CXXFLAGS) main.cpp ./node/node.cpp ./algorithms/bfs.cpp -o ./algorithms/bfs
	# $(CXX) $(CXXFLAGS) main.cpp ./node/node.cpp ./algorithms/dfs.cpp -o ./algorithms/dfs
	# $(CXX) $(CXXFLAGS) main.cpp ./node/node.cpp ./algorithms/ids.cpp -o ./algorithms/ids
	# $(CXX) $(CXXFLAGS) main.cpp ./node/node.cpp ./algorithms/aStar.cpp -o ./algorithms/astar

clean:
	$(CL) -rm main
