./algorithms/agv astar ../inputs/input1.txt
./algorithms/agv astar ../inputs/input2.txt
./algorithms/agv astar ../inputs/input3.txt
./algorithms/agv astar ../inputs/input5x5-5.txt
./algorithms/agv astar ../inputs/input5x13-4.txt
./algorithms/agv astar ../inputs/input9x13-2.txt
./algorithms/agv astar ../inputs/input9x13-5.txt
./algorithms/agv astar ../inputs/input9x14-5.txt
./algorithms/agv astar ../inputs/input16x8-3.txt
./algorithms/agv astar ../inputs/input16x8-5.txt
./algorithms/agv astar ../inputs/input16x9-2.txt
./algorithms/agv astar ../inputs/input16x9-3.txt
./algorithms/agv astar ../inputs/input16x9-4.txt
./algorithms/agv astar ../inputs/input16x9-5.txt
./algorithms/agv astar ../inputs/input19x19-2.txt
./algorithms/agv astar ../inputs/input19x19-5.txt
